services:
  alexa-cookie-service:
    build: .
    container_name: alexa-cookie-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - ./data:/data
