services:
  alexa-cookie-service:
    build: .
    container_name: alexa-cookie-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "58080:58080"
      - "58090:58090"
    volumes:
      - ./data:/data
